### ISSUE TITLE
Platform error sensor.looko2 - Integration 'looko2' not found.

### ISSUE THREAD

**Issue by tajchert** [PiotrMachowski/Home-Assistant-custom-components-Looko2#5]
Po utworzeniu folderu, dodaniu plików i dodaniu następującej konfiguracji:
```
sensor:
  - platform: looko2
    api_key: !secret looko2_token
    name: LookO2
    station_id: 'XYZ'
    monitored_conditions:
      - 'AverageHCHO'
      - 'AveragePM1'
      - 'AveragePM10'
      - 'AveragePM25'
      - 'Color'
      - 'HCHO'
      - 'Humidity'
      - 'PM1'
      - 'PM10'
      - 'PM25'
      - 'Temperature'
    scan_interval:
      hours: 0
      minutes: 20
      seconds: 0
```

Struktura plików:
![image](https://user-images.githubusercontent.com/2962633/94713376-fa7ea880-034a-11eb-9f9f-220139451e80.png)

otrzymuję błąd:
`Platform error sensor.looko2 - Integration 'looko2' not found.`

Home Assistant 0.115.6
